/**
 * @fileoverview HTML tags collection
 */

const tags = {

  // core
  body: 'body',
  head: 'head',
  html: 'html',
  title: 'title',

  // metadata
  base: 'base',
  meta: 'meta',

  // coding
  link: 'link',
  script: 'script',

  // functional
  area: 'area',
  dialog: 'dialog',
  map: 'map',
  noscript: 'noscript',
  slot: 'slot',
  style: 'style',
  template: 'template',

  // text format
  b: 'b',
  bdi: 'bdi',
  bdo: 'bdo',
  blockquote: 'blockquote',
  del: 'del',
  em: 'em',
  h1: 'h1',
  h2: 'h2',
  h3: 'h3',
  h4: 'h4',
  h5: 'h5',
  h6: 'h6',
  i: 'i',
  ins: 'ins',
  mark: 'mark',
  p: 'p',
  pre: 'pre',
  q: 'q',
  rp: 'rp',
  rt: 'rt',
  ruby: 'ruby',
  s: 's',
  small: 'small',
  span: 'span',
  strong: 'strong',
  sup: 'sup',
  u: 'u',
  wbr: 'wbr',

  // data definition
  abbr: 'abbr',
  address: 'address',
  cite: 'cite',
  code: 'code',
  data: 'data',
  dfn: 'dfn',
  kbd: 'kbd',
  samp: 'samp',
  time: 'time',
  var: 'var',

  // semantic
  article: 'article',
  aside: 'aside',
  figcaption: 'figcaption',
  figure: 'figure',
  footer: 'footer',
  header: 'header',
  hgroup: 'hgroup',
  main: 'main',
  menu: 'menu',
  nav: 'nav',
  search: 'search',
  section: 'section',
  summary: 'summary',

  // media
  audio: 'audio',
  img: 'img',
  picture: 'picture',
  source: 'source',
  track: 'track',
  video: 'video',

  // interactive
  a: 'a',
  button: 'button',
  details: 'details',

  // form
  datalist: 'datalist',
  fieldset: 'fieldset',
  form: 'form',
  input: 'input',
  keygen: 'keygen',
  label: 'label',
  legend: 'legend',
  optgroup: 'optgroup',
  option: 'option',
  output: 'output',
  select: 'select',
  textarea: 'textarea',

  // list
  dd: 'dd',
  dl: 'dl',
  dt: 'dt',
  li: 'li',
  ol: 'ol',
  ul: 'ul',

  // table
  caption: 'caption',
  col: 'col',
  colgroup: 'colgroup',
  table: 'table',
  tbody: 'tbody',
  td: 'td',
  tfoot: 'tfoot',
  th: 'th',
  thead: 'thead',
  tr: 'tr',

  // embed
  embed: 'embed',
  iframe: 'iframe',
  object: 'object',
  param: 'param',

  // draw
  br: 'br',
  canvas: 'canvas',
  hr: 'hr',
  meter: 'meter',
  progress: 'progress',

  // divison
  div: 'div',

  // svg
  animate: 'animate',
  animateMotion: 'animateMotion',
  animateTransform: 'animateTransform',
  circle: 'circle',
  clipPath: 'clipPath',
  defs: 'defs',
  desc: 'desc',
  ellipse: 'ellipse',
  feBlend: 'feBlend',
  feColorMatrix: 'feColorMatrix',
  feComponentTransfer: 'feComponentTransfer',
  feComposite: 'feComposite',
  feConvolveMatrix: 'feConvolveMatrix',
  feDiffuseLighting: 'feDiffuseLighting',
  feDisplacementMap: 'feDisplacementMap',
  feDistantLight: 'feDistantLight',
  feDropShadow: 'feDropShadow',
  feFlood: 'feFlood',
  feFuncA: 'feFuncA',
  feFuncB: 'feFuncB',
  feFuncG: 'feFuncG',
  feFuncR: 'feFuncR',
  feGaussianBlur: 'feGaussianBlur',
  feImage: 'feImage',
  feMerge: 'feMerge',
  feMergeNode: 'feMergeNode',
  feMorphology: 'feMorphology',
  feOffset: 'feOffset',
  fePointLight: 'fePointLight',
  feSpecularLighting: 'feSpecularLighting',
  feSpotLight: 'feSpotLight',
  feTile: 'feTile',
  feTurbulence: 'feTurbulence',
  filter: 'filter',
  foreignObject: 'foreignObject',
  g: 'g',
  image: 'image',
  line: 'line',
  linearGradient: 'linearGradient',
  marker: 'marker',
  mask: 'mask',
  metadata: 'metadata',
  mpath: 'mpath',
  path: 'path',
  pattern: 'pattern',
  polygon: 'polygon',
  polyline: 'polyline',
  radialGradient: 'radialGradient',
  rect: 'rect',
  set: 'set',
  stop: 'stop',
  svg: 'svg',
  switch: 'switch',
  symbol: 'symbol',
  text: 'text',
  textPath: 'textPath',
  tspan: 'tspan',
  use: 'use',
  view: 'view',

};
